=> NumPy arrays are strict but fast because:

All items must be the same type (less overhead)
Written in C under the hood (much faster)
Operations run on entire arrays at once (vectorization)

In [1]:
import numpy as np

In [ ]:
#1D Array like a list
[1,2,3,4,5]
#2D Array like a table
[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
#3D Array like a cube

[
    [
        [1, 2], [3, 4]
    ]
    [
        [5, 6], [7, 8]
    ]
]

In Data Science / ML:

1D array → a single column of data (one feature)
2D array → a dataset (rows = samples, columns = features)
3D array → image data (height × width × color channels)

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
#2D array
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


print(matrix)


#Spot the difference:

#Python list: [1, 2, 3] — commas between numbers
#NumPy array: [1 2 3] — no commas (different print format)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Array Properties — Shape, Size, Dimensions

In [ ]:
import numpy as np

arr1D=np.array([1,2,3,4,5])

arr2D = np.array([[1, 2, 3],
                  [4, 5, 6]])
arr3D = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])
# .ndim — how many dimensions?
print(arr1D.ndim)
print(arr2D.ndim)
print(arr3D.ndim)
# .shape — rows x columns (or more dimensions)
print(arr1D.shape)
print(arr2D.shape) # (2, 3)     — 2 rows, 3 columns
print(arr3D.shape) # (2, 2, 2)  — 2 blocks, 2 rows, 2 columns

# .size — total number of elements
print(arr1D.size)   
print(arr2D.size)  
print(arr3D.size)



print(arr1D.dtype)

1
2
3
(5,)
(2, 3)
(2, 2, 2)
5
6
8
int64


Creating Arrays — Common Functions

In [18]:
zeros=np.zeros((3,4),dtype=int)
print(zeros)

print("===========================")

ones=np.ones((3,4),dtype=int)
print(ones)

print("===========================")

seq=np.arange(0,10,2)
print(seq)

print("===========================")

space=np.linspace(0,1,5) # 5 numbers between 0 and 1
print(space)
print("===========================")
rand=np.random.rand(3,3)#random numbers between 0 and 1
print(rand)

print("===========================")

rand_int = np.random.randint(0,100,(3,3))

print(rand_int)

print("===========================")

#Identity matrix

eye=np.eye(3)
print(eye)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.02019169 0.55671265 0.52412199]
 [0.70180698 0.42043912 0.49357332]
 [0.30118045 0.58721925 0.38560851]]
[[94  9 53]
 [43 56 36]
 [87 70 56]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


 Vectorization — The Magic of NumPy
 This is the most important concept in NumPy. Understand this deeply.
Vectorization = apply an operation to the ENTIRE array at once — no loops needed.

In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Multiply entire array by 2 — no loop needed!
print(arr * 2)       # [ 2  4  6  8 10]

# Add 10 to every element
print(arr + 10)      # [11 12 13 14 15]

# Square every element
print(arr ** 2)      # [ 1  4  9 16 25]

# Divide every element
print(arr / 2)       # [0.5 1.  1.5 2.  2.5]

# Operations between two arrays (element-wise)
arr2 = np.array([10, 20, 30, 40, 50])
print(arr + arr2)    # [11 22 33 44 55]
print(arr * arr2)    # [ 10  40  90 160 250]

[ 2  4  6  8 10]
[11 12 13 14 15]
[ 1  4  9 16 25]
[0.5 1.  1.5 2.  2.5]
[11 22 33 44 55]
[ 10  40  90 160 250]


In [21]:
#DS/AI Example
#python# Normalize data — common ML preprocessing step
# Formula: (value - min) / (max - min)

data = np.array([10, 25, 15, 30, 20, 5])

normalized = (data - data.min()) / (data.max() - data.min())
print(normalized)
# [0.2  0.8  0.4  1.0  0.6  0.0]

# ONE LINE — no loops! This is the power.
# With a Python list, you'd need a loop.

[0.2 0.8 0.4 1.  0.6 0. ]


INDEXING & SLICING

In [ ]:
#1D Array indexing
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Forward indexing
print(arr[0])      # 10
print(arr[2])      # 30
print(arr[-1])     # 50  (backward)

# Slicing [start:stop:step] — stop NOT included (L:R rule!)
print(arr[1:4])    # [20 30 40]
print(arr[:3])     # [10 20 30]
print(arr[2:])     # [30 40 50]
print(arr[::2])    # [10 30 50]  every 2nd element
print(arr[::-1])   # [50 40 30 20 10]  reversed

In [2]:
import numpy as np
#2D Array Indexing
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Single element [row, column]
print(matrix[0, 0])    # 10  — row 0, col 0
print(matrix[0, 2])    # 30  — row 0, col 2
print(matrix[1, 1])    # 50  — row 1, col 1
print(matrix[2, 2])    # 90  — row 2, col 2
print(matrix[-1, -1])  # 90  — last row, last col

10
30
50
90
90


In [7]:
#Selecting Rows and Columns
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Select entire ROW
print(matrix[0])        # [10 20 30]  row 0
print(matrix[1])        # [40 50 60]  row 1
print(matrix[1, :])     # [40 50 60]  same thing

# Select entire COLUMN
print(matrix[:, 0])     # [10 40 70]  column 0
print(matrix[:, 1])     # [20 50 80]  column 1
print(matrix[:, 2])     # [30 60 90]  column 2

print(matrix[0, :] )    # row 0,    ALL columns
print(matrix[:, 0] )    # ALL rows, column 0
print(matrix[:, :])     # ALL rows, ALL columns = entire array

[10 20 30]
[40 50 60]
[40 50 60]
[10 40 70]
[20 50 80]
[30 60 90]
[10 20 30]
[10 40 70]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [8]:
#Slicing 2D Arrays (Sub-Matrix)

matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Rows 0 to 1, ALL columns
print(matrix[0:2, :])
# [[10 20 30]
#  [40 50 60]]

# ALL rows, columns 1 to 2
print(matrix[:, 1:3])
# [[20 30]
#  [50 60]
#  [80 90]]

# Rows 0-1, columns 0-1
print(matrix[0:2, 0:2])
# [[10 20]
#  [40 50]]

[[10 20 30]
 [40 50 60]]
[[20 30]
 [50 60]
 [80 90]]
[[10 20]
 [40 50]]


In [9]:
#Basic Boolean Filter
arr = np.array([10, 25, 15, 30, 20, 5])

# Create a boolean mask
mask = arr > 15
print(mask)        # [False  True False  True  True False]

# Apply mask to filter
print(arr[mask])   # [25 30 20]

# One-liner (most common way)
print(arr[arr > 15])   # [25 30 20]


[False  True False  True  True False]
[25 30 20]
[25 30 20]
