=> NumPy arrays are strict but fast because:

All items must be the same type (less overhead)
Written in C under the hood (much faster)
Operations run on entire arrays at once (vectorization)

In [1]:
import numpy as np

In [ ]:
#1D Array like a list
[1,2,3,4,5]
#2D Array like a table
[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
#3D Array like a cube

[
    [
        [1, 2], [3, 4]
    ]
    [
        [5, 6], [7, 8]
    ]
]

In Data Science / ML:

1D array → a single column of data (one feature)
2D array → a dataset (rows = samples, columns = features)
3D array → image data (height × width × color channels)

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
#2D array
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


print(matrix)


#Spot the difference:

#Python list: [1, 2, 3] — commas between numbers
#NumPy array: [1 2 3] — no commas (different print format)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Array Properties — Shape, Size, Dimensions

In [ ]:
import numpy as np

arr1D=np.array([1,2,3,4,5])

arr2D = np.array([[1, 2, 3],
                  [4, 5, 6]])
arr3D = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])
# .ndim — how many dimensions?
print(arr1D.ndim)
print(arr2D.ndim)
print(arr3D.ndim)
# .shape — rows x columns (or more dimensions)
print(arr1D.shape)
print(arr2D.shape) # (2, 3)     — 2 rows, 3 columns
print(arr3D.shape) # (2, 2, 2)  — 2 blocks, 2 rows, 2 columns

# .size — total number of elements
print(arr1D.size)   
print(arr2D.size)  
print(arr3D.size)



print(arr1D.dtype)

1
2
3
(5,)
(2, 3)
(2, 2, 2)
5
6
8
int64


Creating Arrays — Common Functions

In [18]:
zeros=np.zeros((3,4),dtype=int)
print(zeros)

print("===========================")

ones=np.ones((3,4),dtype=int)
print(ones)

print("===========================")

seq=np.arange(0,10,2)
print(seq)

print("===========================")

space=np.linspace(0,1,5) # 5 numbers between 0 and 1
print(space)
print("===========================")
rand=np.random.rand(3,3)#random numbers between 0 and 1
print(rand)

print("===========================")

rand_int = np.random.randint(0,100,(3,3))

print(rand_int)

print("===========================")

#Identity matrix

eye=np.eye(3)
print(eye)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.02019169 0.55671265 0.52412199]
 [0.70180698 0.42043912 0.49357332]
 [0.30118045 0.58721925 0.38560851]]
[[94  9 53]
 [43 56 36]
 [87 70 56]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


 Vectorization — The Magic of NumPy
 This is the most important concept in NumPy. Understand this deeply.
Vectorization = apply an operation to the ENTIRE array at once — no loops needed.

In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Multiply entire array by 2 — no loop needed!
print(arr * 2)       # [ 2  4  6  8 10]

# Add 10 to every element
print(arr + 10)      # [11 12 13 14 15]

# Square every element
print(arr ** 2)      # [ 1  4  9 16 25]

# Divide every element
print(arr / 2)       # [0.5 1.  1.5 2.  2.5]

# Operations between two arrays (element-wise)
arr2 = np.array([10, 20, 30, 40, 50])
print(arr + arr2)    # [11 22 33 44 55]
print(arr * arr2)    # [ 10  40  90 160 250]

[ 2  4  6  8 10]
[11 12 13 14 15]
[ 1  4  9 16 25]
[0.5 1.  1.5 2.  2.5]
[11 22 33 44 55]
[ 10  40  90 160 250]


In [21]:
#DS/AI Example
#python# Normalize data — common ML preprocessing step
# Formula: (value - min) / (max - min)

data = np.array([10, 25, 15, 30, 20, 5])

normalized = (data - data.min()) / (data.max() - data.min())
print(normalized)
# [0.2  0.8  0.4  1.0  0.6  0.0]

# ONE LINE — no loops! This is the power.
# With a Python list, you'd need a loop.

[0.2 0.8 0.4 1.  0.6 0. ]


INDEXING & SLICING

In [ ]:
#1D Array indexing
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Forward indexing
print(arr[0])      # 10
print(arr[2])      # 30
print(arr[-1])     # 50  (backward)

# Slicing [start:stop:step] — stop NOT included (L:R rule!)
print(arr[1:4])    # [20 30 40]
print(arr[:3])     # [10 20 30]
print(arr[2:])     # [30 40 50]
print(arr[::2])    # [10 30 50]  every 2nd element
print(arr[::-1])   # [50 40 30 20 10]  reversed

In [2]:
import numpy as np
#2D Array Indexing
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Single element [row, column]
print(matrix[0, 0])    # 10  — row 0, col 0
print(matrix[0, 2])    # 30  — row 0, col 2
print(matrix[1, 1])    # 50  — row 1, col 1
print(matrix[2, 2])    # 90  — row 2, col 2
print(matrix[-1, -1])  # 90  — last row, last col

10
30
50
90
90


In [7]:
#Selecting Rows and Columns
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Select entire ROW
print(matrix[0])        # [10 20 30]  row 0
print(matrix[1])        # [40 50 60]  row 1
print(matrix[1, :])     # [40 50 60]  same thing

# Select entire COLUMN
print(matrix[:, 0])     # [10 40 70]  column 0
print(matrix[:, 1])     # [20 50 80]  column 1
print(matrix[:, 2])     # [30 60 90]  column 2

print(matrix[0, :] )    # row 0,    ALL columns
print(matrix[:, 0] )    # ALL rows, column 0
print(matrix[:, :])     # ALL rows, ALL columns = entire array

[10 20 30]
[40 50 60]
[40 50 60]
[10 40 70]
[20 50 80]
[30 60 90]
[10 20 30]
[10 40 70]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [8]:
#Slicing 2D Arrays (Sub-Matrix)

matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Rows 0 to 1, ALL columns
print(matrix[0:2, :])
# [[10 20 30]
#  [40 50 60]]

# ALL rows, columns 1 to 2
print(matrix[:, 1:3])
# [[20 30]
#  [50 60]
#  [80 90]]

# Rows 0-1, columns 0-1
print(matrix[0:2, 0:2])
# [[10 20]
#  [40 50]]

[[10 20 30]
 [40 50 60]]
[[20 30]
 [50 60]
 [80 90]]
[[10 20]
 [40 50]]


In [9]:
#Basic Boolean Filter
arr = np.array([10, 25, 15, 30, 20, 5])

# Create a boolean mask
mask = arr > 15
print(mask)        # [False  True False  True  True False]

# Apply mask to filter
print(arr[mask])   # [25 30 20]

# One-liner (most common way)
print(arr[arr > 15])   # [25 30 20]


[False  True False  True  True False]
[25 30 20]
[25 30 20]


In [3]:
#Multiple Conditions
import numpy as np
arr = np.array([10, 25, 15, 30, 20, 5, 35])
# AND condition — both must be true — use &
print(arr[(arr > 10) & (arr < 30)])
# OR condition — at least one true — use |
print(arr[(arr < 10) | (arr > 30)])
# NOT condition — use ~
print(arr[~(arr > 20)])


[25 15 20]
[ 5 35]
[10 15 20  5]


 DS/AI Real Example — Filtering Dataset Rows

In [7]:
import numpy as np

# Dataset: age, income, credit_score
dataset = np.array([
    [25, 40000, 700],
    [35, 80000, 750],
    [28, 45000, 580],   # bad credit
    [45, 120000, 800],
    [22, 25000, 620],   # low income
    [30, 60000, 710]
])

print(dataset.shape)
print(dataset.ndim)



ages=dataset[:,0]
incomes=dataset[:,1]
credits=dataset[:,2]
# Filter: only customers with good credit (>=650)
good_credit = dataset[credits >= 650]
print("Good credit customers:\n", good_credit)

# Filter: high income AND good credit
approved = dataset[(incomes >= 50000) & (credits >= 700)]
print("\nLoan approved:\n", approved)



# Filter: risky customers (low income OR bad credit)
risky = dataset[(incomes < 40000) | (credits < 650)]
print("\nRisky customers:\n", risky)


(6, 3)
2
Good credit customers:
 [[    25  40000    700]
 [    35  80000    750]
 [    45 120000    800]
 [    30  60000    710]]

Loan approved:
 [[    35  80000    750]
 [    45 120000    800]
 [    30  60000    710]]

Risky customers:
 [[   28 45000   580]
 [   22 25000   620]]


In [10]:
#np.where() is like an if-else for arrays:

arr = np.array([10, 25, 15, 30, 20, 5])

# Replace values: if > 15 → "high", else → "low"
result = np.where(arr > 15, "high", "low")
print(result)

# DS/AI Example — label predictions
scores = np.array([0.8, 0.3, 0.9, 0.4, 0.7])
labels = np.where(scores >= 0.5, "Positive", "Negative")
print(labels)

['low' 'high' 'low' 'high' 'high' 'low']
['Positive' 'Negative' 'Positive' 'Negative' 'Positive']


In [11]:
#STATISTICAL FUNCTIONS


import numpy as np

data = np.array([15, 25, 35, 10, 45, 20, 30])

print(np.mean(data))      # 25.71   average
print(np.median(data))    # 25.0    middle value
print(np.std(data))       # 11.27   standard deviation
print(np.var(data))       # 126.94  variance
print(np.min(data))       # 10      smallest
print(np.max(data))       # 45      largest
print(np.sum(data))       # 180     total
print(np.argmin(data))    # 3       INDEX of smallest
print(np.argmax(data))    # 4       INDEX of largest
print(np.cumsum(data))    # cumulative sum

25.714285714285715
25.0
11.157499537009505
124.48979591836734
10
45
180
3
4
[ 15  40  75  85 130 150 180]


In [14]:
#axis = 0 vs axis = 1 
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
# No axis — operates on ALL elements
print(np.mean(matrix))

# axis=0 — operates DOWN columns (column-wise)
print(np.mean(matrix, axis=0))

# axis=1 — operates ACROSS rows (row-wise)
print(np.mean(matrix, axis=1))


50.0
[40. 50. 60.]
[20. 50. 80.]


In [15]:
import numpy as np

# 5 students, 3 exam scores
scores = np.array([
    [85, 92, 78],
    [90, 88, 95],
    [72, 68, 75],
    [95, 98, 92],
    [60, 65, 70]
])

# Average score per student (axis=1 = across row)
student_avg = np.mean(scores, axis=1)
print("Student averages:", student_avg)
# [85.  91.  71.67  95.  65.]

# Average score per exam (axis=0 = down column)
exam_avg = np.mean(scores, axis=0)
print("Exam averages:", exam_avg)
# [80.4  82.2  82. ]

# Best student
best = np.argmax(student_avg)
print(f"Best student: Student {best}")   # Student 3

# Lowest scorer per exam
print("Lowest per exam:", np.min(scores, axis=0))
# [60 65 70]

Student averages: [85.         91.         71.66666667 95.         65.        ]
Exam averages: [80.4 82.2 82. ]
Best student: Student 3
Lowest per exam: [60 65 70]


In [16]:
#SORTING & SEARCHING

arr = np.array([30, 10, 50, 20, 40])

# Sort ascending
print(np.sort(arr))        # [10 20 30 40 50]

# Sort descending
print(np.sort(arr)[::-1])  # [50 40 30 20 10]

# argsort — returns INDICES that would sort the array
indices = np.argsort(arr)
print(indices)             # [1 3 0 4 2]
# arr[1]=10, arr[3]=20, arr[0]=30, arr[4]=40, arr[2]=50

[10 20 30 40 50]
[50 40 30 20 10]
[1 3 0 4 2]


In [18]:
#argsort matters in ML
accuracies = np.array([0.87, 0.91, 0.78, 0.95, 0.88])
model_names = ['LogReg', 'RandomForest', 'SVM', 'XGBoost', 'KNN']

# Get indices sorted by accuracy
ranked = np.argsort(accuracies)[::-1]   # descending
print("Model Rankings:")
for rank, idx in enumerate(ranked, 1):
    print(f"  {rank}. {model_names[idx]}: {accuracies[idx]}")

Model Rankings:
  1. XGBoost: 0.95
  2. RandomForest: 0.91
  3. KNN: 0.88
  4. LogReg: 0.87
  5. SVM: 0.78


In [19]:
arr = np.array([10, 25, 15, 30, 20])

# Find indices where condition is true
indices = np.where(arr > 15)
print(indices)          # (array([1, 3, 4]),)
print(arr[indices])     # [25 30 20]

# Check if any/all elements meet condition
print(np.any(arr > 20))    # True  (at least one)
print(np.all(arr > 5))     # True  (all of them)
print(np.all(arr > 20))    # False (not all)

(array([1, 3, 4]),)
[25 30 20]
True
True
False


In [20]:
#reshape()
#In ML, you'll reshape arrays constantly to match model requirements:

arr = np.array([1, 2, 3, 4, 5, 6])

print(arr.reshape(2, 3))
# [[1 2 3]
#  [4 5 6]]

print(arr.reshape(3, 2))
# [[1 2]
#  [3 4]
#  [5 6]]

# -1 means "calculate this dimension automatically"
print(arr.reshape(-1, 2))   # figure out rows, fix 2 cols
# [[1 2]
#  [3 4]
#  [5 6]]

print(arr.reshape(2, -1))   # fix 2 rows, figure out cols
# [[1 2 3]
#  [4 5 6]]

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [21]:
#flatten() and ravel()
matrix = np.array([[1,2,3],[4,5,6]])

print(matrix.flatten())    # [1 2 3 4 5 6] — returns COPY
print(matrix.ravel())      # [1 2 3 4 5 6] — returns VIEW

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
#transpose of matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print(matrix.shape)       # (2, 3)
print(matrix.T)
# [[1 4]
#  [2 5]
#  [3 6]]
print(matrix.T.shape)     # (3, 2)  rows and cols swapped!

(2, 3)
[[1 4]
 [2 5]
 [3 6]]
(3, 2)


BROADCASTING 
Broadcasting = NumPy's ability to perform operations on arrays of different shapes automatically.



In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr + 10)

[11 12 13 14 15]


In [24]:
#Python equivalent WITHOUT broadcasting:

# Without broadcasting (old way)
result = [x + 10 for x in arr]   # loop needed

# With NumPy broadcasting
result = arr + 10                  # one line, 50x faster

In [27]:
# Add a row vector to every row
print("Row Vector")
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Add a row vector to every row
row = np.array([10, 20, 30])

print(matrix + row)
print("Column Vector")
#Add a Column Vector to Every Column
col = np.array([[10],
                [20],
                [30]])

print(matrix + col)


Row Vector
[[11 22 33]
 [14 25 36]
 [17 28 39]]
Column Vector
[[11 12 13]
 [24 25 26]
 [37 38 39]]


In [28]:
import numpy as np

# Standardize data (z-score normalization)
# Formula: (value - mean) / std
# Used in EVERY ML preprocessing pipeline

data = np.array([
    [25, 40000, 700],
    [35, 80000, 750],
    [28, 45000, 680],
    [45, 120000, 800],
    [30, 60000, 710]
])

# Calculate mean and std for each column
mean = np.mean(data, axis=0)    # [32.6, 69000, 728]
std  = np.std(data,  axis=0)    # [7.4,  29..., 43..]

print("Mean per feature:", mean)
print("Std  per feature:", std)

# Standardize — broadcasting handles shape difference
standardized = (data - mean) / std
print("\nStandardized data:\n", np.round(standardized, 2))

Mean per feature: [3.26e+01 6.90e+04 7.28e+02]
Std  per feature: [7.00285656e+00 2.90516781e+04 4.26145515e+01]

Standardized data:
 [[-1.09 -1.   -0.66]
 [ 0.34  0.38  0.52]
 [-0.66 -0.83 -1.13]
 [ 1.77  1.76  1.69]
 [-0.37 -0.31 -0.42]]


In [29]:
 #MATHEMATICAL OPERATIONS
arr = np.array([1, 4, 9, 16, 25])

print(np.sqrt(arr))       # [1. 2. 3. 4. 5.]
print(np.abs([-3,-1,2]))  # [3 1 2]   absolute value
print(np.exp([1,2,3]))    # [e, e², e³]
print(np.log([1,10,100])) # natural log
print(np.log10([1,10,100])) # log base 10  → [0. 1. 2.]
print(np.power(2, [1,2,3,4])) # [2,4,8,16]

[1. 2. 3. 4. 5.]
[3 1 2]
[ 2.71828183  7.3890561  20.08553692]
[0.         2.30258509 4.60517019]
[0. 1. 2.]
[ 2  4  8 16]


In [ ]:
#Dot Product & Matrix Multiplication
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise multiply then sum
dot = np.dot(a, b)
print(dot)  # 1*4 + 2*5 + 3*6 = 4+10+18 = 32

32


In [31]:
# Shape rules: (m, n) @ (n, p) = (m, p)
# INNER dimensions must match!

A = np.array([[1, 2],
              [3, 4]])      # shape (2, 2)

B = np.array([[5, 6],
              [7, 8]])      # shape (2, 2)

# Method 1: np.dot()
result = np.dot(A, B)

# Method 2: @ operator (modern, preferred)
result = A @ B

print(result)
# [[19 22]
#  [43 50]]

[[19 22]
 [43 50]]


In [32]:
 #DS/AI Example — Why Matrix Multiplication Matters
import numpy as np

# Neural network forward pass (simplified)
# Input: 3 samples, 4 features each
X = np.array([
    [1.0, 2.0, 3.0, 4.0],   # sample 1
    [5.0, 6.0, 7.0, 8.0],   # sample 2
    [9.0, 10., 11., 12.]    # sample 3
])   # shape: (3, 4)

# Weights: 4 inputs → 3 neurons
W = np.random.rand(4, 3)     # shape: (4, 3)

# Bias: one per neuron
b = np.array([0.1, 0.2, 0.3])  # shape: (3,)

# Forward pass: output = X @ W + b
output = X @ W + b           # shape: (3, 3)
print("Output shape:", output.shape)   # (3, 3)
print("Output:\n", np.round(output, 2))

Output shape: (3, 3)
Output:
 [[ 2.57  7.81  4.75]
 [ 6.87 19.12  9.93]
 [11.18 30.43 15.1 ]]


In [33]:
#RANDOM NUMBERS FOR ML
import numpy as np

# Without seed — different every time
print(np.random.rand(3))   # different each run!

# With seed — same result every time
np.random.seed(42)
print(np.random.rand(3))   # [0.374 0.951 0.732] always!

np.random.seed(42)
print(np.random.rand(3))   # [0.374 0.951 0.732] same!

[0.52219653 0.1949429  0.37633725]
[0.37454012 0.95071431 0.73199394]
[0.37454012 0.95071431 0.73199394]


In [34]:
np.random.seed(42)

# rand — uniform distribution (0 to 1)
print(np.random.rand(5))
# [0.374 0.951 0.732 0.599 0.156]

# randn — standard normal distribution (mean=0, std=1)
print(np.random.randn(5))
# [-0.234  1.574 -0.464  0.241 -1.914]

# randint — random integers
print(np.random.randint(0, 100, 5))
# [38 87 12 58 60]

# choice — pick random item(s) from array
arr = np.array([10, 20, 30, 40, 50])
print(np.random.choice(arr, 3))
# [30 10 50]

# shuffle — shuffle in place
data = np.array([1, 2, 3, 4, 5])
np.random.shuffle(data)
print(data)    # [3 1 4 5 2] — shuffled!

# 2D random arrays
weights = np.random.randn(3, 4)   # neural network weights
print(weights.shape)               # (3, 4)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
[ 0.27904129  1.01051528 -0.58087813 -0.52516981 -0.57138017]
[21 88 48 90 58]
[20 40 40]
[1 2 5 4 3]
(3, 4)


In [ ]:
#Normal Distribution
import numpy as np
import matplotlib.pyplot as plt  # you'll have this with Anaconda

np.random.seed(42)

# Generate heights — normally distributed
# mean=170cm, std=10cm, 1000 people
heights = np.random.normal(loc=170, scale=10, size=1000)

print(f"Mean: {np.mean(heights):.1f} cm")    # ~170
print(f"Std:  {np.std(heights):.1f} cm")     # ~10
print(f"Min:  {np.min(heights):.1f} cm")
print(f"Max:  {np.max(heights):.1f} cm")

# Most values fall between 150-190 (within 2 std)
in_range = np.sum((heights >= 150) & (heights <= 190))
print(f"Between 150-190cm: {in_range}/1000")   # ~950 (95%)

Mean: 170.2 cm
Std:  9.8 cm
Min:  137.6 cm
Max:  208.5 cm
Between 150-190cm: 959/1000


In [36]:
import numpy as np

np.random.seed(42)

print("=== ML Data Preparation Pipeline ===\n")

# Step 1: Generate a synthetic dataset
# 100 samples, 4 features
X = np.random.randn(100, 4)
# Generate labels (0 or 1) based on first feature
y = np.where(X[:, 0] > 0, 1, 0)

print(f"Dataset shape: {X.shape}")
print(f"Labels shape:  {y.shape}")
print(f"Class 0: {np.sum(y==0)}, Class 1: {np.sum(y==1)}")

# Step 2: Standardize features (z-score)
mean = np.mean(X, axis=0)
std  = np.std(X,  axis=0)
X_scaled = (X - mean) / std        # broadcasting!

print(f"\nAfter scaling:")
print(f"Mean (should be ~0): {np.round(np.mean(X_scaled, axis=0), 2)}")
print(f"Std  (should be ~1): {np.round(np.std(X_scaled,  axis=0), 2)}")

# Step 3: Train/test split (80/20)
indices = np.arange(100)
np.random.shuffle(indices)
split = 80

X_train = X_scaled[indices[:split]]
X_test  = X_scaled[indices[split:]]
y_train = y[indices[:split]]
y_test  = y[indices[split:]]

print(f"\nTrain: {X_train.shape}, Test: {X_test.shape}")

# Step 4: Simple stats on training data
print(f"\nTraining stats:")
print(f"Feature means: {np.round(np.mean(X_train, axis=0), 3)}")
print(f"Feature stds:  {np.round(np.std(X_train,  axis=0), 3)}")
print(f"Class balance: {np.sum(y_train==0)} vs {np.sum(y_train==1)}")

=== ML Data Preparation Pipeline ===

Dataset shape: (100, 4)
Labels shape:  (100,)
Class 0: 50, Class 1: 50

After scaling:
Mean (should be ~0): [ 0.  0. -0. -0.]
Std  (should be ~1): [1. 1. 1. 1.]

Train: (80, 4), Test: (20, 4)

Training stats:
Feature means: [-0.02  -0.12   0.008  0.02 ]
Feature stds:  [1.032 0.956 1.069 0.991]
Class balance: 41 vs 39
