In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

np.__version__


'2.1.3'

In [2]:
my_list = [0,1, 2, 3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [3]:
type(my_list)

list

In [4]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(10,20)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [11]:
np.arange(20,10)# first arg is always smaller than second arg

array([], dtype=int64)

In [13]:
np.zeros(10)#parameter tuning

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.zeros(10,dtype=int)#hyperparameter tuning

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.zeros([5,4])#2D array with parameter tuning

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.zeros([5,4],dtype=int)#2D array with hyperparameter tuning

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
np.zeros([10,10],dtype=int)#2D array with hyperparameter tuning

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [18]:
np.ones(2,dtype=int)

array([1, 1])

In [19]:
np.ones([5,4],dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [24]:
np.random.rand(3,2)

array([[0.01923758, 0.98999292],
       [0.27507472, 0.44769957],
       [0.59092417, 0.25946059]])

In [39]:
np.random.randint(0,10)

6

In [43]:
np.random.randint(0,10,5)

array([1, 3, 1, 7, 7], dtype=int32)

In [60]:
n=np.random.randint(10,40,(8,10))
print(n)

[[30 26 13 13 30 22 29 13 27 20]
 [21 14 18 30 11 35 37 10 13 11]
 [23 39 23 38 22 19 31 32 31 30]
 [17 36 14 39 32 17 21 18 35 23]
 [15 29 12 18 28 26 28 10 20 23]
 [36 10 36 39 24 14 27 28 16 22]
 [32 35 36 14 20 11 33 10 39 28]
 [30 35 39 29 30 39 31 32 16 17]]


In [59]:
print(n[0])

[32 17 35 37 33 37 34 13 10 36]


In [56]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
#Recap
import numpy as np

In [1]:
my_list = [0,1,2,3,4,5]
print(my_list)

[0, 1, 2, 3, 4, 5]


In [2]:
type(my_list)

list

In [3]:
my_list

[0, 1, 2, 3, 4, 5]

In [7]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [10]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [13]:
np.arange(20,10)#ist arg is greater than 2nd argument

array([], dtype=int64)

In [14]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [ ]:
np.zeros(5)#parameter tuning

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros(5,dtype=int)


array([0, 0, 0, 0, 0])

In [18]:
np.zeros([2,2],dtype=int)

array([[0, 0],
       [0, 0]])

In [20]:
np.zeros([5,4],dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [21]:
np.zeros((10,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [23]:
np.ones(2,dtype=int)

array([1, 1])

In [24]:
np.ones([2,2],dtype=int)

array([[1, 1],
       [1, 1]])

In [25]:
np.ones([4,5],dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
arr

array([0, 1, 2, 3, 4, 5])

In [27]:
np.random.rand(3,2)

array([[0.2932654 , 0.36891891],
       [0.32001677, 0.51401003],
       [0.09452493, 0.53155314]])

In [33]:
np.random.randint(3)

1

In [35]:
np.random.randint(0,10)

1

In [37]:
np.random.randint(0,10,5)

array([8, 2, 6, 2, 5], dtype=int32)

In [39]:
n=np.random.randint(10,40,(8,10))
print(n)

[[20 24 24 36 36 33 14 39 39 35]
 [30 14 20 18 31 39 39 21 15 23]
 [28 13 14 26 20 29 31 30 22 14]
 [26 25 10 11 20 20 16 17 10 31]
 [31 25 17 25 22 13 17 31 18 12]
 [34 27 12 22 37 34 29 36 14 25]
 [35 22 11 15 22 27 17 36 38 30]
 [36 32 23 31 22 28 36 38 39 21]]


In [42]:
print(n[5,2])

12


In [43]:
print(n[0:6])

[[20 24 24 36 36 33 14 39 39 35]
 [30 14 20 18 31 39 39 21 15 23]
 [28 13 14 26 20 29 31 30 22 14]
 [26 25 10 11 20 20 16 17 10 31]
 [31 25 17 25 22 13 17 31 18 12]
 [34 27 12 22 37 34 29 36 14 25]]


In [44]:
print(n)

[[20 24 24 36 36 33 14 39 39 35]
 [30 14 20 18 31 39 39 21 15 23]
 [28 13 14 26 20 29 31 30 22 14]
 [26 25 10 11 20 20 16 17 10 31]
 [31 25 17 25 22 13 17 31 18 12]
 [34 27 12 22 37 34 29 36 14 25]
 [35 22 11 15 22 27 17 36 38 30]
 [36 32 23 31 22 28 36 38 39 21]]


In [46]:
print(n[::-1])

[[36 32 23 31 22 28 36 38 39 21]
 [35 22 11 15 22 27 17 36 38 30]
 [34 27 12 22 37 34 29 36 14 25]
 [31 25 17 25 22 13 17 31 18 12]
 [26 25 10 11 20 20 16 17 10 31]
 [28 13 14 26 20 29 31 30 22 14]
 [30 14 20 18 31 39 39 21 15 23]
 [20 24 24 36 36 33 14 39 39 35]]


In [48]:
print(n[::2])

[[20 24 24 36 36 33 14 39 39 35]
 [28 13 14 26 20 29 31 30 22 14]
 [31 25 17 25 22 13 17 31 18 12]
 [35 22 11 15 22 27 17 36 38 30]]


In [ ]:
print(n[0,5])#comma represents the value to print and : represents the property to print

33


In [50]:
print(n[5,-3])

36


In [51]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [53]:
a=np.arange(6)
a2=a[np.newaxis,:]
a2.shape

(1, 6)

In [55]:
a=np.array([1,2,3,4,5,6])

In [56]:
a=np.array(
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ]
)

In [57]:
print(a[0])

[1 2 3 4]


In [60]:
np.ones((4,3,2), dtype=int)

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [ ]:
#Operations

In [63]:
a=np.random.randint(10,20,10)
print(a)

[14 16 17 12 18 11 18 15 15 16]


In [68]:
arr2 = np.random.randint(0,100,(10,10))
print(arr2)


[[72 90 91 19 10 64 57 96 13 39]
 [87  0  4 87  7 47 76 43  2 54]
 [26 86  1 98 57 99  1 79 30 33]
 [66 44  3 75  1 98 79 10  0 64]
 [70 88 62 14 68 72 41 53 13 78]
 [28 47 12 25 78  6 25 10 36 70]
 [46 43 13 81 47 16 99 74 66 80]
 [41 29 67 26  9 52 63 72 22 72]
 [60 68 67 23 83 87 58 56  5 86]
 [ 8  5 97 28  2 64 96 78 66 78]]


In [69]:
arr2[:]

array([[72, 90, 91, 19, 10, 64, 57, 96, 13, 39],
       [87,  0,  4, 87,  7, 47, 76, 43,  2, 54],
       [26, 86,  1, 98, 57, 99,  1, 79, 30, 33],
       [66, 44,  3, 75,  1, 98, 79, 10,  0, 64],
       [70, 88, 62, 14, 68, 72, 41, 53, 13, 78],
       [28, 47, 12, 25, 78,  6, 25, 10, 36, 70],
       [46, 43, 13, 81, 47, 16, 99, 74, 66, 80],
       [41, 29, 67, 26,  9, 52, 63, 72, 22, 72],
       [60, 68, 67, 23, 83, 87, 58, 56,  5, 86],
       [ 8,  5, 97, 28,  2, 64, 96, 78, 66, 78]], dtype=int32)

1.Array Creation Functions

In [70]:
import numpy as  np

In [71]:
#Create an array from list
a=np.array([1,2,3])
print("Array a:",a)

Array a: [1 2 3]


In [74]:
b=np.arange(0,10,2)
print("Even Spacce Array",b)

Even Spacce Array [0 2 4 6 8]


In [75]:
c = np.linspace(0, 1, 5)  # 5 values evenly spaced between 0 and 1
print("Array c:", c)

Array c: [0.   0.25 0.5  0.75 1.  ]


In [76]:
d = np.zeros((2, 3))  # 2x3 array of zeros
print("Array d:\n", d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [79]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
f=np.eye(4)#identity matrix
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


2.Array Manipulation Functions

In [82]:
a1=np.array([1,2,3])
reshaped=np.reshape(a1,(1,3))
print("Reshaped array:", reshaped)

Reshaped array: [[1 2 3]]
